# Generated by Django 4.2.20 on 2025-03-25 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('chara_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_game_name', models.CharField(max_length=100, unique=True)),
                ('polaris_id', models.CharField(max_length=50, unique=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.rank')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('battle_id', models.AutoField(primary_key=True, serialize=False)),
                ('battle_at', models.DateTimeField()),
                ('battle_type', models.IntegerField(default=2)),
                ('opponent_name', models.CharField(max_length=100)),
                ('opponent_character', models.CharField(max_length=50)),
                ('rounds_won', models.IntegerField()),
                ('rounds_lost', models.IntegerField()),
                ('winner', models.BooleanField()),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_character', to='analytics.character')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='analytics.player')),
            ],
        ),
    ]
