# Generated by Django 4.2.20 on 2025-03-25 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-battle_at']},
        ),
    ]
