# Generated by Django 4.2.20 on 2025-04-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='polaris_id',
            new_name='tekken_id',
        ),
    ]
