# Generated by Django 4.2.20 on 2025-04-10 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_polaris_id_profile_tekken_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
    ]
